AWSTemplateFormatVersion: '2010-09-09'
Description: Lapis' Cloudformation Template

Resources:
  LapisCodeAndImages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lapis-memory-${AWS::AccountId}"
      AccessControl: Private

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: CloudFormationFullAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  LapisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LapisData
      AttributeDefinitions:
        - AttributeName: Author_ID
          AttributeType: S
        - AttributeName: Location
          AttributeType: S
      KeySchema:
        - AttributeName: Author_ID
          KeyType: HASH
        - AttributeName: Location
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Lambda Roles
  LapisDBLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LapisDBLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: LapisPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource: !GetAtt LapisTable.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${LapisCodeAndImages}/*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:LapisFernetSecret*"

              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                Resource: "*"

  LapisSeedLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LapisSeedLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LapisSeedPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt LapisTable.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: "*"

              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                Resource: "*"


  # Lambda Functions
  LapisDBFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LapisDBFn
      Runtime: python3.11
      Handler: db_lambda.handler
      Role: !GetAtt LapisDBLambdaRole.Arn
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref LapisTable
          BUCKET_NAME: !Ref LapisCodeAndImages
          SECRET_NAME: !Ref LapisFernetKey
      Code:
        S3Bucket: !Ref LapisCodeAndImages
        S3Key: DB_lambda.zip

  LapisSeedFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LapisSeedFn
      Runtime: python3.11
      Handler: seed_lambda.handler
      Role: !GetAtt LapisSeedLambdaRole.Arn
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          SECRET_NAME: !Ref LapisFernetKey
          TABLE_NAME: !Ref LapisTable
          EXECUTABLE_NAME: ./src/lapis/inputHandler
      Code:
        S3Bucket: !Ref LapisCodeAndImages
        S3Key: SD_lambda.zip

  LapisFernetKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: LapisAppSecret
      Description: "Fernet key for Lapis' CSE"

  # Log groups
  LapisDBFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LapisDBFn}"
      RetentionInDays: 14

  LapisSeedFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LapisSeedFn}"
      RetentionInDays: 14

  # API Gateway
  LapisHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: LapisHttpApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
          - PUT
        AllowHeaders:
          - "*"

  # Lambda integrations
  DBIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref LapisHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LapisDBFn.Arn}/invocations
      PayloadFormatVersion: "2.0"

  SeedIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref LapisHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LapisSeedFn.Arn}/invocations
      PayloadFormatVersion: "2.0"

  # API Gateway Routes
  SeedGETRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref LapisHttpApi
      RouteKey: "GET /seedInfo"
      Target: !Sub integrations/${SeedIntegration}

  DBPOSTRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref LapisHttpApi
      RouteKey: "POST /items"
      Target: !Sub integrations/${DBIntegration}

  DBGETRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref LapisHttpApi
      RouteKey: "GET /items"
      Target: !Sub integrations/${DBIntegration}

  DBDELETERoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref LapisHttpApi
      RouteKey: "DELETE /items"
      Target: !Sub integrations/${DBIntegration}

  DBPUTRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref LapisHttpApi
      RouteKey: "PUT /items"
      Target: !Sub integrations/${DBIntegration}

  LapisHttpStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref LapisHttpApi
      StageName: prod
      AutoDeploy: true

  # Lambda permissions
  LapisDBFnInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LapisDBFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LapisHttpApi}/*/*/*

  LapisSeedFnInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LapisSeedFn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LapisHttpApi}/*/*/*

Outputs:
  S3BucketName:
    Description: "Bucket for imgs users send to Lapis."
    Value: !Ref LapisCodeAndImages

  DynamoDBTableName:
    Description: "Location data."
    Value: !Ref LapisTable

  SecretARN:
    Description: "ARN of Lapis' stored fernet key."
    Value: !Ref LapisFernetKey
