name: RunTests 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      SECRET_NAME: ${{ secrets.SECRET_NAME }}
      TABLE_NAME: ${{ secrets.TABLE_NAME }}
      TOKEN: ${{ secrets.TOKEN }}
      REGION_NAME: ${{ secrets.REGION_NAME }}

      CACHE_TABLE: ${{ vars.CACHE_TABLE }}
      EXECUTABLE_NAME: ${{ vars.EXECUTABLE_NAME }}
      SEED_CACHE: ${{ vars.SEED_CACHE }}
      SPN: ${{ vars.SPN }}

    steps:
    - name: Check REGION_NAME
      run: |
        if [ -z "$REGION_NAME" ]; then
          echo "REGION_NAME is NOT SET"
        else
          echo "REGION_NAME is set"
        fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
